// This file is intentionally empty.
// All API functions and hooks are generated by orval from the OpenAPI spec.
// Run `npx orval` inside reporthole-fe/ to regenerate after backend changes.
// Generated output: app/api/generated/
